import { cx } from "@/lib/format";
import { Markdown } from "@/components/ui/Markdown";

/* ============================================================
   The README, rendered under the folder.

   GitHub's shape, on the owner's instruction: a repository page is a file list with the
   repository's own README drawn below it, and everything a maintainer wants to say about
   the thing is said there rather than in panels the page invents around it. Four panels
   came off `/blueprints/[owner]/[slug]` in the same pass; this is what stands in their
   place, and the argument for it is that the sentences now come from the artefact instead
   of from the page. The bundle already ships a README — `bundleReadme` in
   `lib/content/bundle-export.ts` writes one into every download — so what renders here is
   the file a reader gets, not a second description of it that can disagree with the first.

   ── The frame is `FileTree`'s ──
   Same border, same `bg-surface-2` header strip, same `≡` glyph the listing draws beside a
   document row. The two boxes are one object stacked: the folder, then the file the folder
   opens with.

   ── No reading column, and that is a standing ruling ──
   `.prose-lane` caps body prose at `--measure` and this body does not take it. The owner
   has corrected the width of this page's copy before, and the instruction that brought
   this component into existence says the description under the blueprint name runs the
   full horizontal space. A README inset to 60-odd characters under a full-width file list
   would reintroduce exactly the two-pages-stacked reading that
   `app/blueprints/[owner]/[slug]/page.tsx` records removing from its body.

   ── Why the rendering is somebody else's ──
   `components/ui/Markdown.tsx` owns the parse and the element mapping, and it is a server
   component that returns React elements and never `dangerouslySetInnerHTML`. Bundle
   READMEs are generated here today, and the same panel will render one that came out of a
   registry row tomorrow; a component that inlined a parser would be the place that has to
   be audited when that happens.
   ============================================================ */

export function ReadmePanel({
  source,
  file,
  className,
}: {
  /** The Markdown itself, already read. Generated by `bundleReadme` for a bundle. */
  source: string;
  /** The name the header strip prints, so the panel names a file that exists on disk. */
  file: string;
  className?: string;
}) {
  return (
    <section
      id="readme"
      aria-labelledby="readme-title"
      className={cx("overflow-hidden rounded-lg border border-line bg-surface", className)}
    >
      {/* The header strip is `FileTree`'s, to the pixel: same paddings, same ground, same
          hairline under it. `≡` is the glyph that listing already draws beside a document,
          so the row reads as one of its own rows lifted out. */}
      <div className="flex items-center gap-3 border-b border-line bg-surface-2 px-5 py-3.5">
        <span aria-hidden className="w-4 shrink-0 text-center text-dim">
          ≡
        </span>
        {/* An `h2`, because this is a section of the page and a reader tabbing headings
            should land on it. The file name IS the heading, which is what GitHub does and
            what keeps the strip from claiming to be a title the file does not have. */}
        <h2 id="readme-title" className="font-mono text-[13px] text-fg">
          {file}
        </h2>
      </div>

      <div className="px-5 py-6">
        <Markdown source={source} />
      </div>
    </section>
  );
}
