import puppeteer from "puppeteer-core";
const OUT = "/private/tmp/claude-501/-Users-alessandro-Github-darkprint/5ae12563-a8e9-4a9a-ad5c-e5843ee213b4/scratchpad/shots";
const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new" });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 1000, deviceScaleFactor: 2 });
await p.goto("http://localhost:3100/mcp", { waitUntil: "networkidle0" });
await new Promise(r => setTimeout(r, 900));
await p.screenshot({ path: `${OUT}/mcp-centred.png` });
console.log("ok");
await b.close();
