/* ============================================================
   T091 — AC2 and AC3, through `serveFile`

   The half of this task that a caller can see: `serveFile`
   prefers the frozen artefact, and still serves a release that
   predates the freeze.

   ── why this file exists at all, given t090/serve.test.ts ──
   `tests/server/t090/serve.test.ts`'s AC6 cell has measured this
   property since T050 and has been red the whole time, and its
   own comments record why it CANNOT go further: "the fixture does
   not persist anything before re-scoring: it *cannot*, because
   the write verb belongs to another task". §T091's AC3 forbids
   weakening that cell and this suite does not touch it.

   What this partition can do that it cannot is the point: T091
   may call `persistArtefacts`, so the frozen half of the property
   gets a witness here — with its own control — instead of resting
   on one criterion in another task's file that nobody could make
   green from inside.

   ── every release here has a run-unique digest ──
   See `uniqueDot` in fixtures.ts. `S3_BUCKET` is one bucket for
   the whole machine and `keyForDigest` puts no run in the key, so
   a suite that seeded a shipped bundle unperturbed would freeze
   its fixture over somebody else's real artefact and delete the
   key at teardown.
   ============================================================ */

import { afterAll, beforeAll, describe, expect, it } from "vitest";

import type { Actor } from "@/lib/server/policy";
import type { ObjectStorage } from "@/lib/db";
import type { ExportedFile } from "@/lib/content/bundle-export";

import { outcomeOf, expectThrewExactly } from "../t090/contract";
import {
  EXPORT,
  NO_SUCH_FILE,
  asServedFile,
  decode,
  describeValue,
  loadExport,
  requiredFn,
  type Served,
} from "./contract";
import {
  bundleBySlug,
  clearWritten,
  deriveDownloadCounter,
  downloadsFor,
  expectNoObject,
  freeze,
  putRaw,
  scratchDatabase,
  seedAccount,
  seedOntology,
  seedRelease,
  storage,
  uniqueDot,
  type DownloadCounter,
  type Scratch,
  type SeededAccount,
  type SeededRelease,
} from "./fixtures";

const ANONYMOUS: Actor = { kind: "anonymous" };

/** The bundle t090/serve.test.ts serves from, so both partitions measure the same content. */
const SUBJECT = "schema-forge-etl";

/** A string no exporter can emit, so "prefers the frozen artefact" EXCLUDES the generated bytes. */
const MARKER = "t091-this-text-came-out-of-the-bucket";

let scratch: Scratch;
let store: ObjectStorage;
let owner: SeededAccount;
let stranger: SeededAccount;

/** Never frozen. The release that predates `persistArtefacts` — which is every release there is. */
let pristine: SeededRelease;
/** Frozen with a marked folder, for the preference cell and for contentType. */
let marked: SeededRelease;
/** Frozen verbatim, then re-scored. The AC6 property. */
let rescoredFrozen: SeededRelease;
/** Not frozen, then re-scored identically. The control that proves the re-score is not inert. */
let rescoredPlain: SeededRelease;
/** Frozen with one file removed, for the R2 ruling. */
let partial: SeededRelease;
/** Private, owned by somebody else, frozen. The authorization-ordering cell. */
let secret: SeededRelease;
/** Frozen, for the download counter. */
let counted: SeededRelease;
/** Frozen, for the contentType comparison. Its own release so no cell depends on another running. */
let typed: SeededRelease;
/** A same-bundle pair: `pinned` is frozen and marked, `moving` is the newer version. */
let pinned: SeededRelease;
let moving: SeededRelease;

let strangerActor: Actor;

beforeAll(async () => {
  scratch = await scratchDatabase("serve");
  store = storage();
  await seedOntology(scratch.db);

  owner = await seedAccount(scratch, "t091owner");
  stranger = await seedAccount(scratch, "t091stranger");
  strangerActor = { kind: "account", accountId: stranger.accountId, handle: stranger.handle };

  const entry = bundleBySlug(SUBJECT);
  const seed = async (
    marker: string,
    account: SeededAccount = owner,
    extra: { visibility?: "public" | "private"; bundleId?: string; version?: string } = {},
  ): Promise<SeededRelease> =>
    seedRelease(scratch, account, entry, {
      dot: uniqueDot(entry.bundle.dot, marker),
      slug: `${SUBJECT}-${marker}`,
      ...extra,
    });

  pristine = await seed("pristine");
  marked = await seed("marked");
  rescoredFrozen = await seed("rescored-frozen");
  rescoredPlain = await seed("rescored-plain");
  partial = await seed("partial");
  counted = await seed("counted");
  typed = await seed("typed");
  secret = await seed("secret", stranger, { visibility: "private" });

  /* One bundle, two releases, so "digest before version" has an input on which the two orderings
     disagree. The second release differs only in a DOT comment, which moves its digest. */
  pinned = await seed("pinned");
  moving = await seedRelease(scratch, owner, entry, {
    bundleId: pinned.bundleId,
    version: "2.0.0",
    slug: pinned.slug,
    dot: uniqueDot(entry.bundle.dot, "moving"),
  });
}, 300_000);

/*
 * The explicit hook timeouts are not decoration. `vitest.config.ts` raises `hookTimeout` to 30s
 * and says why; creating a database, migrating it and seeding nine releases crosses that under
 * the parallel worktree load this repository runs at — and a hook that fails runs no test, so
 * the run reports passes beside failed FILES and exit 1 rather than a red per criterion.
 */
afterAll(async () => {
  if (store !== undefined) await clearWritten(store);
  if (scratch !== undefined) await scratch.drop();
}, 180_000);

/* --------------------- calling the module under test, bound last --------------------- */

async function callServeFile(
  ref: { ownerHandle: string; slug: string; version?: string; digest?: string },
  path: string,
  actor: Actor = ANONYMOUS,
): Promise<unknown> {
  const mod = await loadExport();
  return requiredFn(mod, "serveFile")(scratch.db, actor, ref, path);
}

/** The generated folder for one release, as `ExportedFile[]`, through T090's published verb. */
async function generatedFolder(
  release: SeededRelease,
  actor: Actor = ANONYMOUS,
): Promise<readonly ExportedFile[]> {
  const mod = await loadExport();
  return (await requiredFn(mod, "exportRelease")(
    scratch.db,
    actor,
    release.bundleId,
    release.digest,
  )) as readonly ExportedFile[];
}

function refFor(release: SeededRelease): { ownerHandle: string; slug: string; digest: string } {
  return { ownerHandle: release.ownerHandle, slug: release.slug, digest: release.digest };
}

async function serve(release: SeededRelease, path: string, actor: Actor = ANONYMOUS): Promise<Served> {
  return asServedFile(
    await callServeFile(refFor(release), path, actor),
    `\`serveFile\` for \`${path}\` at ${release.digest}`,
  );
}

/**
 * The same folder the generator produces, with one file's text carrying a marker.
 *
 * `exportRelease` builds the base, and that is not the tautology it can look like: what
 * discriminates in every cell below is the MARKER, which `exportRelease` cannot produce and
 * which no code path in `lib/server/export/**` has ever seen. Deriving the rest of the folder
 * from the generator is what keeps the frozen artefact a plausible one — a synthetic folder
 * would also pass, and would leave "the frozen bytes are structurally a real export" unmeasured.
 */
function markOneFile(
  files: readonly ExportedFile[],
  path: string,
): { files: readonly ExportedFile[]; text: string } {
  const original = files.find((file) => file.path === path);
  if (original === undefined) {
    throw new Error(
      `The generated folder holds no \`${path}\`, so there is nothing to mark. It holds: ` +
        `${files.map((f) => f.path).join(", ")}.`,
    );
  }
  const text = `${original.text}\n${MARKER}\n`;
  return { files: files.map((file) => (file.path === path ? { ...file, text } : file)), text };
}

/* --------------------- AC2, the fallback half --------------------- */

describe("AC2 — a release that predates the freeze still serves", () => {
  /*
   * FIRST, and not by accident. §T091: "The fallback is not a convenience: every release
   * currently in the database was written before T100 shipped `persistArtefacts`." A suite whose
   * cells all planted an artefact first would go green against an implementation that served
   * only frozen releases and 404'd the entire existing archive.
   */

  it("serves generated bytes when nothing is frozen at the digest", async () => {
    await expectNoObject(store, pristine.digest);

    const served = await serve(pristine, "README.md");
    expect(
      served.path,
      "`serveFile` reported a path other than the one it was asked for.",
    ).toBe("README.md");
    expect(
      decode(served.bytes),
      `\`README.md\` for a release with no frozen artefact came back without its own digest in ` +
        `it. The generated README quotes the release digest, so this is the cheapest evidence ` +
        `that the bytes are this release's rather than empty or another's.`,
    ).toContain(pristine.digest);
    expect(
      decode(served.bytes),
      "A release nothing has frozen served bytes carrying this suite's frozen-artefact marker, " +
        "which nothing but a planted object can contain.",
    ).not.toContain(MARKER);
  }, 120_000);

  it("serves EVERY file of an unfrozen release, not only the one the first cell asked for", async () => {
    /*
     * The first cell passes against an implementation that special-cased `README.md`, and a
     * release is a folder. This is the cell that would fail if the fallback were wired up for
     * one path — which is a plausible shape for a preference branch bolted onto the front of a
     * function that used to do one thing.
     */
    await expectNoObject(store, pristine.digest);
    const folder = await generatedFolder(pristine);
    expect(folder.length, "The pristine release exported nothing.").toBeGreaterThan(4);

    for (const file of folder) {
      const served = await serve(pristine, file.path);
      expect(
        decode(served.bytes),
        `\`serveFile\` and \`exportRelease\` disagree about \`${file.path}\` in a release with ` +
          `no frozen artefact. With nothing in the bucket they are two views of one generated ` +
          `folder and there is nothing for them to differ over.`,
      ).toBe(file.text);
    }
  }, 180_000);

  it("falls back rather than failing when the object at the digest is not the container", async () => {
    /*
     * The second reason a release can have no usable frozen artefact, and the one that decides
     * whether this feature can be rolled back safely. `lib/server/publish/artefacts.ts`:
     * "An object written before this format existed, or truncated, is indistinguishable to a
     * reader from a release that was never frozen — and both have the same correct answer, which
     * is to fall back to generating from Postgres. **A throw here would turn a servable release
     * into a 500.**"
     *
     * Asserted at `serveFile` rather than at `readPersisted`, because it is `serveFile` that
     * owes the caller an answer: a `readPersisted` returning `undefined` correctly and a
     * `serveFile` that propagated a decode failure would both be visible only here.
     */
    const junk = await seedRelease(scratch, owner, bundleBySlug(SUBJECT), {
      dot: uniqueDot(bundleBySlug(SUBJECT).bundle.dot, "junk"),
      slug: `${SUBJECT}-junk`,
    });
    await expectNoObject(store, junk.digest);
    /* Through `storage.put`, not `persistArtefacts`: the point is bytes the codec never wrote. */
    await putRaw(store, junk.digest, new TextEncoder().encode("this is not the container {"));

    const outcome = await outcomeOf(() => callServeFile(refFor(junk), "README.md"));
    expect(
      outcome.kind,
      `\`serveFile\` threw for a release whose stored object does not decode.\n` +
        `  The object is unreadable; the RELEASE is not. Postgres still holds everything needed ` +
        `to generate the folder, and a 500 here would take down every release whose artefact was ` +
        `written by an older encoder — the exact failure \`decodeArtefacts\` returns \`undefined\` ` +
        `instead of throwing in order to avoid.\n` +
        `  It threw: ${outcome.kind === "throw" ? outcome.message : ""}`,
    ).toBe("value");

    const served = asServedFile(
      outcome.kind === "value" ? outcome.value : undefined,
      "`serveFile` over an undecodable object",
    );
    expect(
      decode(served.bytes),
      "`serveFile` fell back but did not generate this release's bytes.",
    ).toContain(junk.digest);
  }, 180_000);
});

/* --------------------- AC2, the preference half --------------------- */

describe("AC2 — serveFile prefers the frozen artefact", () => {
  it("returns the frozen bytes, which the generator cannot have produced", async () => {
    /*
     * The measurement, and the reason it is a marker rather than a comparison.
     *
     * A cell asserting `served === frozenText` where the frozen text IS the generated text
     * passes against an implementation that never opened the bucket. The marker is a string no
     * code path in `lib/server/export/**` has ever contained, so its presence EXCLUDES the
     * generated output rather than merely admitting the frozen one — common-traps: a cell whose
     * comment names a concrete bad output must exclude it, and `toBeInstanceOf(Date)` admits
     * `new Date(0)`.
     *
     * `serveFile` takes no storage handle, so there is no argument this suite can wrap to observe
     * the read. The bytes are the only instrument, which is why they have to be bytes only the
     * bucket could have supplied.
     */
    const folder = await generatedFolder(marked);
    const { files, text } = markOneFile(folder, "README.md");

    /* Premise: the generated bytes and the frozen bytes really differ, so the cell can tell them
       apart at all. Checked rather than assumed — an inert fixture is a cell that proves nothing. */
    const generated = folder.find((file) => file.path === "README.md")?.text;
    expect(generated, "The generated folder holds no README.md.").toBeDefined();
    expect(text, "The marked text and the generated text are identical.").not.toBe(generated);

    await expectNoObject(store, marked.digest);
    const before = await serve(marked, "README.md");
    expect(
      decode(before.bytes),
      "Before anything was frozen, `serveFile` already returned the marker. The fixture is not " +
        "measuring what it claims to.",
    ).not.toContain(MARKER);

    await freeze(store, marked.digest, files);

    const after = await serve(marked, "README.md");
    expect(
      decode(after.bytes),
      `\`serveFile\` returned bytes with no frozen-artefact marker in them after ` +
        `\`persistArtefacts\` froze a marked folder at ${marked.digest}.\n` +
        `  §T091 AC2: \`serveFile\` PREFERS the frozen artefact. The marker cannot be generated ` +
        `— no code path in ${EXPORT} contains that string — so bytes without it are bytes that ` +
        `came from Postgres while a frozen artefact was sitting in the bucket unread. That is ` +
        `precisely the state T100's merge left behind: written and never read.`,
    ).toContain(MARKER);
    expect(
      decode(after.bytes),
      "`serveFile` returned bytes that carry the marker but are not the frozen text. The frozen " +
        "artefact is the release's bytes, not a base for the server to amend.",
    ).toBe(text);
  }, 180_000);

  it("serves every path of the release out of the frozen folder", async () => {
    /*
     * The preference cell above would pass against an implementation that consulted the bucket
     * for `README.md` alone. Every path in the frozen folder is marked here, so a single
     * generated file among them is visible.
     */
    const release = await seedRelease(scratch, owner, bundleBySlug(SUBJECT), {
      dot: uniqueDot(bundleBySlug(SUBJECT).bundle.dot, "all-marked"),
      slug: `${SUBJECT}-all-marked`,
    });
    const folder = await generatedFolder(release);
    const marks = folder.map((file) => ({ ...file, text: `${file.text}\n${MARKER} ${file.path}\n` }));

    await expectNoObject(store, release.digest);
    await freeze(store, release.digest, marks);

    for (const file of marks) {
      const served = await serve(release, file.path);
      expect(
        decode(served.bytes),
        `\`${file.path}\` came back without its frozen marker while every other file in the same ` +
          `folder was frozen alongside it. A release is a folder, and a preference wired up for ` +
          `one path serves half a release from each of two sources.`,
      ).toBe(file.text);
    }
  }, 240_000);
});

/* --------------------- AC3's criterion, witnessed from this partition --------------------- */

describe("AC6 — one digest serves one answer across a B-08 re-score", () => {
  it("holds for a frozen release, and the same re-score MOVES an unfrozen one", async () => {
    /*
     * **The criterion this whole task exists for, with the control that makes it a measurement.**
     *
     * `tests/server/t090/serve.test.ts`'s AC6 cell measures exactly this and has been red since
     * T050, because its fixture cannot persist: "the write verb belongs to another task". That
     * cell is untouched by this suite and §T091 AC3 forbids weakening it. This one is the same
     * property from a partition that IS allowed to call `persistArtefacts`.
     *
     * The mechanism is t090's, copied deliberately rather than invented: `release.autonomy` and
     * `release.security` are columns on the row the digest names, B-08 re-scores them when an
     * ontology version is released, and `bundle-export.ts` quotes all four values verbatim into
     * `README.md`. So one digest serves different bytes over time at the address `/mcp` calls
     * load-bearing precisely because it does not move. The re-score is written directly because
     * scoring is T040's and B-08's and no verb for it is published to this task.
     *
     * ── THE CONTROL, AND WHY THE CELL IS WORTHLESS WITHOUT IT ──
     * "The frozen release's bytes did not change" is satisfied by a re-score that changed
     * nothing. That is not hypothetical: a column rename, an analysis shape that stopped
     * reaching the README, or an `update` matching zero rows all turn this cell green while
     * measuring nothing — and a zero is a claim about an instrument until something proves
     * otherwise. So an UNFROZEN release of the same content gets the identical re-score in the
     * same transaction-less breath, and its bytes must MOVE. The frozen half and the control
     * half fail with different sentences, so a red says which of the two happened.
     */
    await expectNoObject(store, rescoredFrozen.digest);
    await expectNoObject(store, rescoredPlain.digest);

    const folder = await generatedFolder(rescoredFrozen);
    await freeze(store, rescoredFrozen.digest, folder);

    const frozenBefore = decode((await serve(rescoredFrozen, "README.md")).bytes);
    const plainBefore = decode((await serve(rescoredPlain, "README.md")).bytes);

    for (const release of [rescoredFrozen, rescoredPlain]) {
      const rescored = await scratch.pool.query(
        `update "release"
            set autonomy = $1::jsonb, security = $2::jsonb
          where bundle_id = $3 and digest = $4`,
        [
          JSON.stringify({
            label: "Human-gated",
            rationale: "re-scored under a later ontology (B-08)",
            contributions: [],
          }),
          JSON.stringify({
            level: 2,
            rationale: "re-scored under a later ontology (B-08)",
            findings: [],
          }),
          release.bundleId,
          release.digest,
        ],
      );
      expect(
        rescored.rowCount,
        `The re-score updated ${String(rescored.rowCount)} rows for ${release.digest}, not 1. ` +
          `Nothing below could distinguish a frozen artefact from a regenerated one.`,
      ).toBe(1);
    }

    const plainAfter = decode((await serve(rescoredPlain, "README.md")).bytes);
    expect(
      plainAfter,
      `THE CONTROL FAILED, AND THIS IS NOT A DEFECT IN T091.\n` +
        `  \`README.md\` for the UNFROZEN release is byte-identical before and after a re-score ` +
        `that updated its row. The re-score is therefore invisible in the served bytes, and the ` +
        `frozen half of this cell would pass against an implementation that never opened the ` +
        `bucket.\n` +
        `  Look at whether \`bundle-export.ts\` still quotes \`analysis.autonomy\` and ` +
        `\`analysis.security\` into the README, and whether \`serveFile\` caches. Fix the ` +
        `instrument before reading anything else in this file.`,
    ).not.toBe(plainBefore);

    const frozenAfter = decode((await serve(rescoredFrozen, "README.md")).bytes);
    expect(
      frozenAfter,
      `\`README.md\` at digest ${rescoredFrozen.digest} CHANGED after a B-08 re-score, with the ` +
        `digest unchanged and a frozen artefact present in the bucket.\n` +
        `  AC6 is "fetching by digest returns the bytes of THAT release": one digest must not ` +
        `serve two answers. This is the case a newer release cannot exercise, because a newer ` +
        `release has a newer digest — and it is the case that persisting alone does not fix, ` +
        `which is why this task exists. The control in this same cell confirms the re-score is ` +
        `visible, so the frozen artefact was written and not read.`,
    ).toBe(frozenBefore);
  }, 240_000);
});

/* --------------------- R2: the frozen folder is authoritative for its own digest --------------------- */

describe("a path missing from a PRESENT frozen folder refuses", () => {
  it("throws the published `no such file` form rather than generating the missing file", async () => {
    /*
     * **RULED R2 by the orchestrator, and it is the one cell where this suite and a
     * contract-following implementation could both be right and disagree.**
     *
     * `readPersisted` collapses three situations into one `undefined`: no object, an object that
     * does not decode, and an object that decodes and does not hold the path. The published
     * signature cannot tell the third from the first, so a reading in which all three fall back
     * to Postgres is what the signature alone suggests — R1.
     *
     * R2 was ruled instead, and the reason is the criterion rather than the type: R1 serves a
     * MIXED folder — the old files frozen, a newer one generated off a re-scored present row —
     * and a folder that is half-frozen is not the release's bytes. A release frozen before
     * `bundle-export.ts` grew a file 404s that file, permanently, and that is the ruling working
     * rather than failing.
     *
     * The assertion is at `serveFile` and not at `readPersisted` deliberately: R2 needs a
     * mechanism the published return type does not have, several are defensible, and this cell
     * is correct under every one of them because it asserts what the CALLER receives.
     *
     * ── the control ──
     * The refusal has to be caused by the freeze and not by the path being absent for a boring
     * reason, so the same path is served from an unfrozen release of the same content first and
     * must come back with bytes.
     */
    const folder = await generatedFolder(partial);
    const victim = folder.find((file) => file.path !== "README.md");
    expect(
      victim,
      "The generated folder holds fewer than two files, so nothing can be left out of the freeze.",
    ).toBeDefined();
    const path = (victim as ExportedFile).path;

    /* CONTROL: the path is servable when nothing is frozen. */
    await expectNoObject(store, pristine.digest);
    const control = await serve(pristine, path);
    expect(
      control.bytes.length,
      `THE CONTROL FAILED: \`${path}\` does not serve from an UNFROZEN release either, so the ` +
        `refusal below would not be evidence about the freeze.`,
    ).toBeGreaterThan(0);

    await expectNoObject(store, partial.digest);
    await freeze(
      store,
      partial.digest,
      folder.filter((file) => file.path !== path),
    );

    /* Premise: the file the freeze omits is one the generator would have produced. Without this
       the cell is about a path that never existed, which every reading refuses identically. */
    expect(
      folder.map((file) => file.path),
      `\`${path}\` is not in the generated folder, so leaving it out of the freeze exhibits ` +
        `nothing: R1 and R2 give the same answer for a path neither source holds.`,
    ).toContain(path);

    const outcome = await outcomeOf(() => callServeFile(refFor(partial), path));
    if (outcome.kind === "value") {
      const served = asServedFile(outcome.value, `\`serveFile\` for the omitted \`${path}\``);
      throw new Error(
        `\`serveFile\` returned ${served.bytes.length} bytes for \`${path}\`, which the frozen ` +
          `folder at ${partial.digest} does not contain and which the generator does.\n` +
          `  RULED R2: the frozen folder is authoritative for its own digest. Answering this ` +
          `path from Postgres serves a MIXED folder — the rest of it frozen, this file generated ` +
          `off today's row — and a half-frozen folder is not "the bytes of that release", which ` +
          `is the whole criterion.\n` +
          `  This is the one place a blind suite and a contract-following implementation can both ` +
          `be right and disagree: the published \`Promise<Uint8Array | undefined>\` cannot express ` +
          `R2, so an implementer reading the signature alone builds R1. If you are that ` +
          `implementer, the ruling is real and the SIGNATURE is what needs to change — take it to ` +
          `the orchestrator rather than to this file.`,
      );
    }
    expectThrewExactly(outcome, NO_SUCH_FILE, `\`serveFile\` for the omitted \`${path}\``);
  }, 240_000);

  it("does not move the download counter on that refusal", async () => {
    /*
     * **An existing ruling, applied to a path its author could not reach.**
     *
     * `tests/server/t090/downloads.test.ts` already holds this for the refusal T090 has: "a
     * refused path served no file and an absent release served no file, so neither is a
     * download", and "a counter that moves on a refused path is one anybody can inflate". That
     * cell refuses through the GENERATED file list, and it cannot reach the refusal R2 creates,
     * because it has no frozen artefact and no verb to make one.
     *
     * So this is not a new rule and not a guess: the ruling is unconditional, and T091 opens a
     * second door into the same room. It is also the shape wave-blind warns about from the other
     * side — "assert what the writer LEFT BEHIND, not only that it threw" — because a
     * `serveFile` that recorded the download and *then* discovered the path was missing satisfies
     * every `rejects.toThrow` a reviewer would write.
     *
     * The counter is derived rather than named, for the reason t090's fixture gives: nothing
     * published says which table a download lands in. The hole is re-frozen here rather than
     * inherited, so this cell does not depend on its neighbour having run.
     */
    const mod = await loadExport();
    const record = requiredFn(mod, "recordDownload");
    const counter: DownloadCounter = await deriveDownloadCounter(
      scratch,
      async (target) => record(scratch.db, target),
      `t091-refusal-probe-${process.pid}`,
    );

    const folder = await generatedFolder(partial);
    const victim = folder.find((file) => file.path !== "README.md");
    expect(victim, "The generated folder holds fewer than two files.").toBeDefined();
    const path = (victim as ExportedFile).path;
    await freeze(store, partial.digest, folder.filter((file) => file.path !== path));

    const before = await downloadsFor(scratch, counter, partial.bundleId);
    const outcome = await outcomeOf(() => callServeFile(refFor(partial), path));
    const after = await downloadsFor(scratch, counter, partial.bundleId);

    expect(
      outcome.kind,
      `PREMISE: the R2 refusal did not happen, so there is no refusal to count against. See the ` +
        `cell above — this one says nothing until that one is green.`,
    ).toBe("throw");
    expect(
      after - before,
      `A path refused because the frozen folder does not hold it moved the download counter by ` +
        `${after - before}.\n` +
        `  Nothing was served, so nothing was downloaded. T090 already rules this for the ` +
        `refusal it can reach — "a counter that moves on a refused path is one anybody can ` +
        `inflate" — and R2 opens a second refusal that ruling's author had no frozen artefact to ` +
        `exhibit.\n` +
        `  A \`serveFile\` that records the download and THEN discovers the path is missing ` +
        `satisfies every assertion that only checks it threw.`,
    ).toBe(0);
  }, 240_000);
});

/* --------------------- D1: the freeze is not an authorization bypass --------------------- */

describe("preferring the frozen artefact does not move the visibility check", () => {
  it("still answers `undefined` for a private release after its artefact is frozen", async () => {
    /*
     * **The cell most likely to fire, and the only one here whose failure is a privacy defect
     * reachable from an anonymous request.**
     *
     * D-90-01 gives `serveFile`'s `undefined` one meaning — the release is absent, or the actor
     * may not see it — and that is a property of the ANSWER, not of which branch produced it.
     * The natural shape for "prefer the frozen artefact" is a lookup at the top of the function,
     * before the release row has been read and therefore before anybody knows who owns it or
     * whether it is public. An implementation in that shape hands a private release's bytes to
     * anyone who can guess `(ownerHandle, slug, digest)` — and the digest is exactly what a
     * fork, a mirror or a former collaborator already has.
     *
     * The cell carries its own control: the same release is asked for BEFORE the freeze and must
     * already be `undefined`. If that premise fails the defect is T090's and predates this task,
     * and the message says so rather than charging T091 for it.
     */
    const before = await callServeFile(refFor(secret), "README.md");
    expect(
      before,
      `PREMISE FAILED, AND IT IS NOT T091's.\n` +
        `  A private release owned by another account answered ${describeValue(before)} to an ` +
        `anonymous caller with NOTHING frozen in the bucket. That is T090's B-03 and D-90-01, ` +
        `and it is broken before this task's code runs. The cell below cannot say anything about ` +
        `the freeze until this is fixed.`,
    ).toBeUndefined();

    /* The owner may export their own release, which is how the folder to freeze is obtained. */
    const folder = await generatedFolder(secret, strangerActor);
    expect(folder.length, "The private release exported nothing to freeze.").toBeGreaterThan(0);

    await expectNoObject(store, secret.digest);
    await freeze(store, secret.digest, folder);

    const after = await callServeFile(refFor(secret), "README.md");
    expect(
      after,
      `\`serveFile\` answered ${describeValue(after)} to an ANONYMOUS caller for a PRIVATE ` +
        `release owned by another account, and it answered \`undefined\` for the same reference ` +
        `moments earlier with nothing in the bucket.\n` +
        `  Freezing the artefact is what changed, so the frozen-artefact lookup is happening ` +
        `BEFORE the visibility check. D-90-01 makes \`undefined\` a property of the answer and ` +
        `not of the branch: a caller must not be able to tell whether a release they may not see ` +
        `happens to have been frozen, and must certainly not receive its bytes.\n` +
        `  The digest is not a secret. It is printed in every README, quoted in \`factory.dot\`, ` +
        `and held by every fork and every former collaborator.`,
    ).toBeUndefined();
  }, 240_000);

  it("still serves a private release to its own owner from the frozen artefact", async () => {
    /*
     * The other half, and it is not symmetry for its own sake: a "fix" for the cell above that
     * consulted the bucket only for public releases would pass it while quietly denying owners
     * the frozen bytes of their own private ones — the criterion inverted rather than met.
     *
     * The marker is what makes this the frozen path rather than the fallback.
     */
    const release = await seedRelease(scratch, stranger, bundleBySlug(SUBJECT), {
      dot: uniqueDot(bundleBySlug(SUBJECT).bundle.dot, "secret-owner"),
      slug: `${SUBJECT}-secret-owner`,
      visibility: "private",
    });
    const folder = await generatedFolder(release, strangerActor);
    const { files, text } = markOneFile(folder, "README.md");

    await expectNoObject(store, release.digest);
    await freeze(store, release.digest, files);

    const served = await serve(release, "README.md", strangerActor);
    expect(
      decode(served.bytes),
      "The owner of a private release did not receive its frozen bytes. A visibility check that " +
        "runs before the bucket must still reach the bucket once it passes.",
    ).toBe(text);
  }, 240_000);
});

/* --------------------- D2: the download event survives the new branch --------------------- */

describe("the frozen path still records exactly one download", () => {
  it("counts one for a frozen serve and one for an unfrozen serve", async () => {
    /*
     * T090 publishes `recordDownload` as "called by serveFile and serveCard exactly once each",
     * unconditionally. An early return that answers from the bucket and goes home is the natural
     * way to write a preference branch, and it silently stops the counter for exactly the
     * releases that are popular enough to have been published recently.
     *
     * The counter is LOCATED rather than named: nothing published says which table or column a
     * download lands in, so `deriveDownloadCounter` drives it three times on a probe refId and
     * takes the single field that went 1 -> 3. `refId` is `bundle.id` for a release file, which
     * the T090 block does publish.
     */
    const mod = await loadExport();
    const record = requiredFn(mod, "recordDownload");
    const counter: DownloadCounter = await deriveDownloadCounter(
      scratch,
      async (target) => record(scratch.db, target),
      `t091-download-probe-${process.pid}`,
    );

    const folder = await generatedFolder(counted);
    await expectNoObject(store, counted.digest);

    /* Unfrozen first, so both halves are measured on the same counter in the same database. */
    const plainBefore = await downloadsFor(scratch, counter, pristine.bundleId);
    await serve(pristine, "README.md");
    const plainAfter = await downloadsFor(scratch, counter, pristine.bundleId);
    expect(
      plainAfter - plainBefore,
      `A serve with NO frozen artefact moved the download counter by ${plainAfter - plainBefore}, ` +
        `not 1. This is the pre-existing path, so the instrument is what to look at first.`,
    ).toBe(1);

    await freeze(store, counted.digest, folder);
    const frozenBefore = await downloadsFor(scratch, counter, counted.bundleId);
    await serve(counted, "README.md");
    const frozenAfter = await downloadsFor(scratch, counter, counted.bundleId);
    expect(
      frozenAfter - frozenBefore,
      `A serve from the FROZEN artefact moved the download counter by ` +
        `${frozenAfter - frozenBefore}, not 1, while the same serve from an unfrozen release ` +
        `moved it by exactly 1 in this cell.\n` +
        `  T090 publishes \`recordDownload\` as called by \`serveFile\` exactly once, with no ` +
        `exception for where the bytes came from. A preference branch that returns early skips ` +
        `the counter for precisely the releases new enough to have been frozen — and B-14's ` +
        `"one event per served file" then measures the archive's past rather than its present.`,
    ).toBe(1);
  }, 240_000);
});

/* --------------------- D3: the shape of the answer does not depend on its source --------------------- */

describe("a frozen file and a generated file are the same kind of answer", () => {
  it("reports the same contentType for one path whether or not it is frozen", async () => {
    /*
     * `ServedFile` is `{ path, bytes, contentType }` and the container stores `{ path, text }` —
     * no content type at all. So the frozen branch has to re-derive it from the path, and the
     * cheap way to get that wrong is to hand back a constant on the branch that has no file
     * extension logic wired into it yet.
     *
     * The oracle is not hand-written and no content-type table is published: the expectation is
     * whatever the unfrozen path answers for the same filename. D-90-04 has a route write the
     * body "at its own content type", and a caller must not be able to tell which source served
     * it.
     *
     * -- WHAT THIS CELL IS NOT --
     * It is a CONSISTENCY check between two branches of one module, so it passes against an
     * implementation answering a constant `application/octet-stream` on both. That absolute is
     * held elsewhere and deliberately not restated here: `tests/server/t090/serve.test.ts` pins
     * "gives the three file kinds three different content types" on the generated path, and a
     * second copy of that judgement in this partition would be two authors of one rule. The
     * division is the point -- T090 owns WHAT a content type must be, this task owns that the new
     * branch does not change it -- and it is written down because a green here reads like
     * coverage of content types and is not.
     */
    const folder = await generatedFolder(typed);
    const paths = ["README.md", ...folder.map((f) => f.path).filter((p) => p !== "README.md")].slice(
      0,
      4,
    );
    expect(
      paths.length,
      "Fewer than three files to compare content types across; one extension would not " +
        "distinguish a re-derived type from a constant.",
    ).toBeGreaterThanOrEqual(3);

    await expectNoObject(store, typed.digest);
    await freeze(store, typed.digest, folder);
    for (const path of paths) {
      const frozen = await serve(typed, path);
      const generated = await serve(pristine, path);
      expect(
        frozen.contentType,
        `\`${path}\` is served as \`${frozen.contentType}\` from the frozen artefact and ` +
          `\`${generated.contentType}\` when generated. One path, one kind of file — a caller ` +
          `must not be able to tell which source answered it.`,
      ).toBe(generated.contentType);
      expect(
        frozen.path,
        "A frozen file reported a path other than the one asked for.",
      ).toBe(path);
    }
  }, 240_000);
});

/* --------------------- the T090 clause the freeze could quietly break --------------------- */

describe("digest still resolves before version once a freeze exists", () => {
  it("serves the pinned release's frozen bytes for a ref carrying a newer version", async () => {
    /*
     * backend.md §T090: "`serveFile` resolves `digest` **before** `version`, and a `version`
     * reference is a convenience that moves while a digest reference never does."
     *
     * t090/serve.test.ts already measures that clause. It cannot measure it with a frozen
     * artefact in play, and that combination is where a new failure lives: an implementation
     * that resolved the reference to a release row FIRST and then looked the bucket up by the
     * row's digest is correct here, while one that looked the bucket up by whatever digest the
     * ref happened to carry — or by the version's — is not. Both pass t090's version of this
     * cell, because neither of them has a bucket in it.
     */
    const folder = await generatedFolder(pinned);
    const { files, text } = markOneFile(folder, "README.md");
    await expectNoObject(store, pinned.digest);
    await freeze(store, pinned.digest, files);

    expect(
      pinned.digest,
      "The two releases of this bundle share a digest, so nothing below distinguishes them.",
    ).not.toBe(moving.digest);

    const served = asServedFile(
      await callServeFile(
        {
          ownerHandle: pinned.ownerHandle,
          slug: pinned.slug,
          digest: pinned.digest,
          version: moving.version,
        },
        "README.md",
      ),
      "`serveFile` with the pinned digest and the newer version",
    );
    expect(
      decode(served.bytes),
      `A reference carrying digest ${pinned.digest} and version ${moving.version} did not come ` +
        `back with the frozen bytes of the digest's own release. The digest is resolved first, ` +
        `and \`/mcp\` calls that distinction load-bearing.`,
    ).toBe(text);
  }, 240_000);
});

/* --------------------- what this file's GREENS mean today --------------------- */

/*
 * ── THREE CELLS HERE PASS AGAINST A MODULE THAT NEVER OPENS THE BUCKET, AND THAT IS DISCLOSED
 *    RATHER THAN LEFT TO BE DISCOVERED ──
 *
 * Measured at the blind hand-off, `npx vitest run tests/server/t091/serve-frozen.test.ts`:
 * 6 failed | 6 passed (12), 0 skipped, one failed FILE, exit 1. An all-green suite is a claim
 * about an instrument, and so is a partly-green one — so here is what each green is worth
 * BEFORE `readPersisted` exists:
 *
 *   DISCRIMINATING ALREADY — these two would red today if the fallback were broken, and they are
 *   the ones that stand between this task and an implementation that serves only frozen releases:
 *     - "serves generated bytes when nothing is frozen at the digest"
 *     - "serves EVERY file of an unfrozen release"
 *
 *   INERT TODAY, ARMED FOR THE IMPLEMENTATION — each passes now because `serveFile` never reads
 *   the bucket, so both branches of the comparison are the same branch. Each becomes a real
 *   measurement the moment the frozen path exists, and each is aimed at a specific way of
 *   getting that path wrong:
 *     - "falls back rather than failing when the object at the digest is not the container"
 *       -> arms against a decode failure propagating as a 500.
 *     - "still answers `undefined` for a private release after its artefact is frozen"
 *       -> arms against the bucket being consulted before the visibility check. **The one whose
 *          failure would be a privacy defect reachable from an anonymous request.**
 *     - "counts one for a frozen serve and one for an unfrozen serve"
 *       -> arms against an early return that skips `recordDownload`.
 *     - "reports the same contentType for one path whether or not it is frozen"
 *       -> arms against a frozen branch that hands back a constant type.
 *
 * Reporting a green as covered when it cannot yet fail is the same error as reporting a red as a
 * defect when it is a named dependency, and this task exists because the second one was made
 * twice in two merge logs.
 */
