/* ============================================================
   One-time generator for the hero wordmark's letter outline paths.

   Run manually (not part of `npm run build`) whenever MARK below
   changes, or whenever the display font changes away from Space
   Grotesk Semibold (600):

     WORDMARK_FONT_PATH=/path/to/SpaceGrotesk-SemiBold.ttf \
       node --experimental-strip-types --disable-warning=MODULE_TYPELESS_PACKAGE_JSON \
       scripts/generate-wordmark-paths.ts

   Output is committed as components/hero/wordmark-paths.ts — no font-parsing
   dependency exists at runtime or at `next build` time, only in this script.
   ============================================================ */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
// `opentype.js`'s CJS bundle (dist/opentype.js) isn't statically analyzable by
// Node's ESM/CJS interop (no `exports.xxx = ` pattern cjs-module-lexer can pick
// up), so `import * as opentype from "opentype.js"` resolves every named member
// to `undefined` at runtime even though it typechecks. A default import gets the
// whole `module.exports` object instead, which is what actually has `.parse` etc.
// at runtime; `@types/opentype.js` has no explicit default export, so
// `esModuleInterop` (on in tsconfig.json) synthesizes one typed as the full
// namespace, so this still typechecks the same way `opentype.parse(...)` etc. did.
import opentype from "opentype.js";

/** `components/hero/Wordmark.tsx`'s `MARK` constant. Keep the two in sync by hand. */
const MARK = "DarkPrint";

/** The em-square height the generated paths are scaled to; `Wordmark.tsx`'s overlay SVG
    sizes its viewBox to match. Arbitrary but must match on both sides. */
const UNITS_PER_EM_SIZE = 100;

const fontPath = process.env.WORDMARK_FONT_PATH;
if (fontPath === undefined || fontPath === "") {
  throw new Error(
    "Set WORDMARK_FONT_PATH to a local Space Grotesk SemiBold (600) .ttf/.otf file. " +
      "Download the static family from https://fonts.google.com/specimen/Space+Grotesk",
  );
}

const buffer = readFileSync(fontPath);
const arrayBuffer = buffer.buffer.slice(
  buffer.byteOffset,
  buffer.byteOffset + buffer.byteLength,
);
const font = opentype.parse(arrayBuffer as ArrayBuffer);

interface WordmarkLetterPath {
  char: string;
  /** SVG path `d` attribute, in a `UNITS_PER_EM_SIZE`-tall em box, drawn from x=0. */
  d: string;
  /** Horizontal advance to the next letter's origin, same units. */
  advance: number;
}

const letters: WordmarkLetterPath[] = [];
for (const char of MARK) {
  const glyph = font.charToGlyph(char);
  const path = glyph.getPath(0, 0, UNITS_PER_EM_SIZE);
  // `@types/opentype.js` declares `advanceWidth` as `number | undefined` (it's
  // unset on synthetic/notdef glyphs); every real glyph pulled off a parsed font
  // via `charToGlyph` has one, so treat a missing value as the font being broken
  // rather than papering over it with a cast or a `!`.
  if (glyph.advanceWidth === undefined) {
    throw new Error(`Glyph for character "${char}" has no advanceWidth`);
  }
  const advance = (glyph.advanceWidth * UNITS_PER_EM_SIZE) / font.unitsPerEm;
  letters.push({ char, d: path.toPathData(2), advance });
}

const output = `/* ============================================================
   Generated by scripts/generate-wordmark-paths.ts — do not hand-edit.
   Regenerate if MARK in components/hero/Wordmark.tsx changes, or if
   the display font changes away from Space Grotesk Semibold (600).
   ============================================================ */

export interface WordmarkLetterPath {
  char: string;
  d: string;
  advance: number;
}

/** One entry per character of "${MARK}", in a ${UNITS_PER_EM_SIZE}-unit-tall em box. */
export const WORDMARK_LETTER_PATHS: readonly WordmarkLetterPath[] = ${JSON.stringify(letters, null, 2)} as const;
`;

const outPath = fileURLToPath(new URL("../components/hero/wordmark-paths.ts", import.meta.url));
writeFileSync(outPath, output);
console.log(`Wrote ${letters.length} letter paths to components/hero/wordmark-paths.ts`);
