// Builds the staging package the converter reads as "darkprint".
//
// Two problems it solves at once. The repo ships no .d.ts, so the prop
// extractor produced `[key: string]: unknown` for all 182 components — the
// contract the design agent codes against was empty. And the extractor finds
// its entry through `package.json` "types", which this app has no reason to
// declare. Rather than add generated files to the repo root (tsconfig's
// include is `**/*.ts`, so they would land in the app's own typecheck), the
// package is assembled here and node_modules/darkprint points at it.
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const pkg = join(repo, '.design-sync/.cache/pkg');
const types = join(pkg, 'types');

rmSync(types, { recursive: true, force: true });
mkdirSync(pkg, { recursive: true });

// tsc exits non-zero on lib/db's .ts-extension imports even when excluded from
// the program's roots, so the emit is judged by its output, not its exit code.
try {
  execFileSync('npx', ['tsc', '-p', '.design-sync/tsconfig.dts.json'], { cwd: repo, stdio: 'pipe' });
} catch { /* checked below */ }
if (!existsSync(join(types, 'components'))) throw new Error('declaration emit produced no components/ tree');

const cfg = JSON.parse(readFileSync(join(repo, '.design-sync/config.json'), 'utf8'));
const lines = [], missing = [];
for (const [name, src] of Object.entries(cfg.componentSrcMap)) {
  const rel = src.replace(/\.tsx?$/, '');
  if (!existsSync(join(types, `${rel}.d.ts`))) { missing.push(name); continue; }
  lines.push(`export { ${name} } from './${rel}';`);
}
writeFileSync(join(types, 'index.d.ts'),
  `// GENERATED by .design-sync/scripts/gen-types.mjs — the package's type entry.\n` +
  `// One explicit re-export per component: a barrel of \`export *\` would drop the\n` +
  `// names two files share (WatchButton, BlueprintGraph) as ambiguous.\n` +
  lines.sort().join('\n') + '\n');

// A component declared with no parameter has no props, but the extractor's
// "no first parameter" path falls through to `[key: string]: unknown` — which
// tells the design agent it may pass anything. Say the true thing instead.
// Hand-written bodies belong in cfg.dtsPropsForPins and win over this.
const noProps = {};
for (const [name, src] of Object.entries(cfg.componentSrcMap)) {
  const dts = join(types, `${src.replace(/\.tsx?$/, '')}.d.ts`);
  if (!existsSync(dts)) continue;
  const rx = new RegExp(`declare function ${name}\\(\\s*\\)`);
  if (rx.test(readFileSync(dts, 'utf8'))) noProps[name] = '  /** Takes no props. */';
}
cfg.dtsPropsFor = { ...noProps, ...(cfg.dtsPropsForPins ?? {}) };
writeFileSync(join(repo, '.design-sync/config.json'), JSON.stringify(cfg, null, 2) + '\n');
console.log(`dtsPropsFor: ${Object.keys(noProps).length} zero-prop components pinned`);

// The runtime entry, mirroring the barrel. The converter's own synthesized entry
// is `export * from` every component file, and ESM drops a name two modules both
// export: BlueprintGraph and WatchButton are each declared twice here, so both
// came out undefined on window.DarkPrint. Explicit re-exports name a winner —
// in each case the file named after the component, the other being a private
// helper inside a larger file.
writeFileSync(join(pkg, 'entry.mjs'),
  `// GENERATED by .design-sync/scripts/gen-types.mjs — the bundle's runtime entry.\n` +
  Object.entries(cfg.componentSrcMap)
    .filter(([n]) => lines.some((l) => l.startsWith(`export { ${n} }`)))
    .map(([n, src]) => `export { ${n} } from './${src}';`)
    .sort().join('\n') + '\n');

writeFileSync(join(pkg, 'package.json'), JSON.stringify({
  name: 'darkprint', version: '0.1.0', private: true, types: 'types/index.d.ts',
}, null, 2) + '\n');

// Every cfg.* path field resolves against the package root, so the config home
// has to be reachable from here too: cfg.tsconfig and cfg.extraFonts both live
// under .design-sync/.
// `lib` is here because cfg.tsconfig is read through this package, so the
// tsconfig's own baseUrl resolves `@/*` relative to the package root.
for (const d of ['components', 'lib', 'docs', '.design-sync']) {
  const link = join(pkg, d);
  rmSync(link, { recursive: true, force: true });
  symlinkSync(join(repo, d), link, 'dir');
}

// cssEntry is bounded to the package root, so the stylesheet is copied in.
mkdirSync(join(pkg, 'styles'), { recursive: true });
cpSync(join(repo, '.design-sync/.cache/darkprint.css'), join(pkg, 'styles/darkprint.css'));

console.log(`types: ${lines.length} components in barrel${missing.length ? `, ${missing.length} missing: ${missing.join(', ')}` : ''}`);
