// Freezes the slice of the server-only content archive that components render.
//
// `lib/content/index.ts` says SERVER ONLY in its own header: it reads `content/`
// off disk at module scope. Four components call into it, and every call site
// passes a compile-time constant, so the reachable data is a fixed, tiny set.
// This runs the real loader under Node and emits it as a browser module, which
// is why those cards show the actual archive rather than empty state.
//
// Re-run whenever `content/` changes: the snapshot is the archive at build time.
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tsconfigPathsPlugin } from '../../.ds-sync/lib/bundle.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
const cache = resolve(repo, '.design-sync/.cache');
mkdirSync(cache, { recursive: true });

// The call sites, verbatim. Keep in step with the components if they change.
const entry = resolve(cache, '.snapshot-entry.ts');
writeFileSync(entry, `
import { cardSource, getNodeCard, bundleSource } from "@/lib/content";
import { contentVocabulary } from "@/lib/content/read";
const CARD_REF = "code-builder@1.0.0";
const STARTER = "starter-software-factory";
process.stdout.write(JSON.stringify({
  cardSource: { [CARD_REF]: cardSource(CARD_REF) ?? null },
  nodeCard: { "code-builder@1.0.0": getNodeCard("code-builder", "1.0.0") ?? null },
  bundleSource: { [STARTER]: bundleSource(STARTER) },
  // NOT the built OntologyView: it carries methods (byKind, validate) that JSON
  // drops, and a components that calls one at module scope takes the whole
  // bundle down. Snapshot the constructor's input; the shim calls the real
  // constructor, which is isomorphic and already in the bundle.
  ontologyExtensions: contentVocabulary()?.terms ?? [],
}));
`);

const bundled = resolve(cache, '.snapshot-run.mjs');
await build({
  entryPoints: [entry],
  outfile: bundled,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  packages: 'external',
  plugins: [tsconfigPathsPlugin(resolve(repo, '.design-sync/tsconfig.node.json'))],
  logLevel: 'warning',
});

const json = execFileSync(process.execPath, [bundled], { cwd: repo, maxBuffer: 64 * 1024 * 1024 }).toString();
const data = JSON.parse(json);

const out = resolve(cache, 'content-shim.ts');
writeFileSync(out, `// GENERATED by .design-sync/scripts/snapshot-content.mjs — do not edit.
// Browser stand-in for the server-only "@/lib/content" barrel, carrying the
// exact archive slice the components ask for. Aliased in tsconfig.sync.json.
import { ontologyView, CORE_ONTOLOGY } from "@/lib/core";

const DATA = ${JSON.stringify(data, null, 2)} as const;

export function cardSource(ref: string): string | undefined {
  return (DATA.cardSource as Record<string, string | null>)[ref] ?? undefined;
}

export function getNodeCard(id: string, version?: string) {
  const key = version === undefined ? id : \`\${id}@\${version}\`;
  return (DATA.nodeCard as Record<string, unknown>)[key] ?? undefined;
}

export function bundleSource(slug: string) {
  return (DATA.bundleSource as Record<string, { dot: string; cards: { file: string; text: string }[] }>)[slug]
    ?? { dot: "", cards: [] };
}

// The real constructor from lib/core, which CLAUDE.md keeps isomorphic. Calling
// it here means byKind/validate and the rest behave exactly as in the app;
// only the archive's extension terms are frozen. Memoized like the original.
let view: ReturnType<typeof ontologyView> | undefined;
export function getOntologyView() {
  return (view ??= ontologyView(CORE_ONTOLOGY, DATA.ontologyExtensions as never));
}
`);

rmSync(entry, { force: true });
rmSync(bundled, { force: true });
const kb = (s) => Math.round(s / 1024);
console.log(`content snapshot: card=${data.cardSource[Object.keys(data.cardSource)[0]] ? 'yes' : 'MISSING'} dot=${data.bundleSource['starter-software-factory']?.dot?.length ?? 0}b ontologyExtensions=${data.ontologyExtensions.length} terms -> ${kb(Buffer.byteLength(json))}KB`);
