/* ============================================================
   T250 — AC1, and the plan's own shape

   No database. §T250: "`planImport` takes no `Db` and is pure over
   the content tree, which is what makes AC1 checkable before
   anything is written" — so a digest mismatch is caught without a
   database and without a partial import to unwind. These cells hold
   that promise to its word: nothing in this file opens Postgres,
   and every one of them would still run with the compose stack
   down.

   ── the standard ──
   AC1 is "the digest the site prints today", and
   `public/bundles/<slug>/README.md` line 7 prints it. Those are
   committed generated bytes produced by `lib/content`, which is
   this task's FORBIDDEN, so the standard has a different author
   from the thing measured against it. `oracle.test.ts` validates it
   and falsifies it before any cell here uses it.

   ── one cell per bundle, and the list is monotonic ──
   `it.each(printedDigests())`, so the SCAN decides how many cells
   exist. A `public/bundles/` that lost six directories would
   silently shrink AC1 to a third of its domain; the completeness
   guard that stops that is a cell in `oracle.test.ts`.

   ── bind last ──
   Every cell reads its premise and its expected value BEFORE it
   touches `@/lib/server/seed`. An early bind reds the cell at the
   absent module while being correct about its own subject, and
   hides whether anything below it ever ran.
   ============================================================ */

import { describe, expect, it } from "vitest";

import { cardDigest } from "@/lib/core";
import { nodeCardVersions } from "@/lib/content";

import {
  DIGEST,
  EXPECTED_BUNDLES,
  EXPECTED_CARD_FILES,
  EXPECTED_CARD_IDS,
  IMPORT_PLAN_KEYS,
  PLAN_BUNDLE_KEYS,
  PLAN_CARD_KEYS,
  REGISTRY_HANDLE,
  RELEASES_PER_BUNDLE,
  VISIBILITIES,
  assertCount,
  assertKeys,
  bundleSlugs,
  cardFiles,
  cardIds,
  printedDigests,
  type Namespace,
} from "./contract";
import { plannedOnce } from "./fixtures";

const planned = plannedOnce();

interface PlanBundle {
  slug: string;
  digest: string;
  releases: unknown;
}

interface PlanCard {
  cardId: string;
  version: string;
  digest: string;
  visibility: string;
}

function bundlesOf(plan: Namespace): PlanBundle[] {
  const bundles = plan.bundles;
  if (!Array.isArray(bundles)) {
    throw new Error(`ImportPlan.bundles is not an array; it is ${typeof bundles}.`);
  }
  return bundles as PlanBundle[];
}

function cardsOf(plan: Namespace): PlanCard[] {
  const cards = plan.cards;
  if (!Array.isArray(cards)) {
    throw new Error(`ImportPlan.cards is not an array; it is ${typeof cards}.`);
  }
  return cards as PlanCard[];
}

/** Exact equality, never `includes`. D-250-13: a substring match is how two cells become one. */
function bundleNamed(plan: Namespace, slug: string): PlanBundle | undefined {
  return bundlesOf(plan).find((b) => b.slug === slug);
}

describe("AC1: each of the nine bundles hashes to the digest the site prints today", () => {
  it.each(printedDigests())(
    "$slug plans the digest the README prints",
    async ({ slug, digest }) => {
      /* Premise first, and it is about the STANDARD rather than about the subject: a printed
         digest that is not a digest would make the comparison below meaningless in the direction
         that looks like success. */
      expect(digest).toMatch(DIGEST);

      const plan = await planned();
      const bundle = bundleNamed(plan, slug);

      expect(
        bundle,
        `the plan carries no bundle with slug exactly "${slug}". ` +
          `It carries: ${bundlesOf(plan)
            .map((b) => b.slug)
            .sort()
            .join(", ")}`,
      ).toBeDefined();
      /* The whole digest, compared as a whole. A prefix comparison here would accept a bundle
         whose content differs past the eighth character, which is precisely what a content
         address exists to refuse. */
      expect(bundle?.digest).toBe(digest);
    },
  );

  it("plans exactly the nine bundles the archive carries, by name", () => {
    /* Element-wise against the directory listing rather than by count: nine and nine with
       different names has passed a check in this repository before. */
    return planned().then((plan) => {
      expect(
        bundlesOf(plan)
          .map((b) => b.slug)
          .sort(),
      ).toEqual([...bundleSlugs()]);
      expect(bundlesOf(plan)).toHaveLength(EXPECTED_BUNDLES);
    });
  });
});

describe("the plan's shape", () => {
  it("publishes exactly the three members the block names", async () => {
    const plan = await planned();
    assertKeys(plan, IMPORT_PLAN_KEYS, "ImportPlan");
  });

  /**
   * D-250-01's second half, and it is the reason `runImport` needs the loader rather than the
   * plan: "a plan carrying bytes would make it a second copy of the content tree with its own
   * staleness". The key-set assertion above already forbids a fifth member on the plan; this one
   * says the same thing one level down, where a `dot` or a `cardFiles` would actually be put.
   */
  it("carries identity and not content: no bytes on any entry", async () => {
    const plan = await planned();
    for (const bundle of bundlesOf(plan)) {
      assertKeys(bundle, PLAN_BUNDLE_KEYS, `ImportPlan.bundles["${bundle.slug}"]`);
    }
    for (const card of cardsOf(plan)) {
      assertKeys(card, PLAN_CARD_KEYS, `ImportPlan.cards["${card.cardId}@${card.version}"]`);
    }
  });

  it("plans one release per bundle (D-250-03)", async () => {
    const plan = await planned();
    const wrong = bundlesOf(plan)
      .filter((b) => assertCount(b.releases, `${b.slug}.releases`) !== RELEASES_PER_BUNDLE)
      .map((b) => `${b.slug}=${String(b.releases)}`);
    expect(wrong).toEqual([]);
  });

  it("names the registry handle D-250-04 publishes", async () => {
    const plan = await planned();
    expect(plan.registryHandle).toBe(REGISTRY_HANDLE);
  });

  /* A cell reading `plan.ontologyVersion` stood here, labelled as NOT discriminating: the
     member had two live readings, the overlay's own `version` and the core vocabulary's, and
     both were `"0.1.0"` so the cell could not tell them apart. 0009 removed the member and
     both readings with it, which settles the ambiguity by deletion rather than by choice. */
});

describe("AC1's other half: the 57 card files", () => {
  it("plans one entry per card FILE, not one per card id", async () => {
    const plan = await planned();
    const refs = cardsOf(plan)
      .map((c) => `${c.cardId}@${c.version}`)
      .sort();
    /* 57 and 53 are different numbers and the difference is the trap: `allNodeCards()` answers
       53 because four ids carry two versions. A plan built through it would be short by four and
       would read as full coverage. */
    expect(refs).toEqual(cardFiles().map((f) => f.replace(/\.yaml$/, "")).sort());
    expect(refs).toHaveLength(EXPECTED_CARD_FILES);
    expect(new Set(cardsOf(plan).map((c) => c.cardId)).size).toBe(EXPECTED_CARD_IDS);
  });

  /**
   * Re-attribution is digest-safe by construction, so the digest the plan carries for a card has
   * to be the one `cardDigest` computes over the archive's own document, with the archive's own
   * author still on it. `oracle.test.ts` shows separately that changing the author moves none of
   * the 57, which is what makes both AC1 and AC4 satisfiable at once.
   */
  it("plans the digest lib/core computes for every one of the 57", async () => {
    const expected = new Map<string, string>();
    for (const id of cardIds()) {
      for (const record of nodeCardVersions(id)) {
        const card = ((record as { card?: unknown }).card ?? record) as {
          id: string;
          version: string;
        };
        expected.set(`${card.id}@${card.version}`, cardDigest(card as never));
      }
    }
    expect(expected.size).toBe(EXPECTED_CARD_FILES);

    const plan = await planned();
    /* The cell is named "every one of the 57", so it asserts the count as well as the values.
       Without this line it filters the entries the plan HAPPENS to carry and is green against a
       plan of one card — measured: a 53-of-57 plan left this cell untouched. */
    expect(cardsOf(plan)).toHaveLength(EXPECTED_CARD_FILES);
    const wrong = cardsOf(plan)
      .filter((c) => c.digest !== expected.get(`${c.cardId}@${c.version}`))
      .map((c) => `${c.cardId}@${c.version}: ${c.digest} vs ${expected.get(`${c.cardId}@${c.version}`)}`);
    expect(wrong).toEqual([]);
  });

  it("marks every archive card public, the archive having no private half", async () => {
    const plan = await planned();
    const wrong = cardsOf(plan)
      .filter((c) => c.visibility !== "public")
      .map((c) => `${c.cardId}@${c.version}=${c.visibility}`);
    expect(wrong).toEqual([]);
    /* And the union is still two-valued. AC6 is withdrawn (D-250-02) and the private arm is
       therefore unreachable from `content/**` — asserted here so that "no private card" stays a
       statement about the ARCHIVE rather than becoming a statement about the type. */
    expect([...VISIBILITIES].sort()).toEqual(["private", "public"]);
  });
});

describe("the plan is pure over the content tree", () => {
  /**
   * Two calls, same answer. §T250 says `planImport` is pure, and D-250-01's own argument is that
   * `readContent()` memoizes at module scope — so a second call that disagreed with the first
   * would mean something in the plan is being read from outside the content tree.
   *
   * Compared as JSON rather than by identity: returning the same OBJECT twice satisfies purity
   * and so does building an equal one, and this cell has no reason to prefer either.
   */
  it("answers the same plan twice", async () => {
    const first = await planned();
    const { planImport } = await import("./contract").then(async (c) => ({
      planImport: await c.bind("planImport"),
    }));
    const second = (await planImport()) as Namespace;
    expect(JSON.stringify(second)).toBe(JSON.stringify(first));
  });
});
